### ISSUE TITLE
Errors - New and old

### ISSUE THREAD

**Issue by ostracizado** [luuuis/hass_wibeee#52]
I've noticed that since last week I'm constantly having to manually reload the integration, or the sensors will be and stay "unavailable".

To the old error, during the startup:
```
Logger: custom_components.wibeee.api
Source: custom_components/wibeee/api.py:26
Integration: wibeee (documentation, issues)
First occurred: 10:19:21 (1 occurrences)
Last logged: 10:19:21

Error getting http://192.168.2.139/en/status.xml after 3 retries: TimeoutError:
```
Now there was other one, that I can't replicate:
```
Logger: homeassistant.components.sensor
Source: custom_components/wibeee/api.py:39
Integration: Sensor (documentation, issues)
First occurred: 07:31:16 (1 occurrences)
Last logged: 07:31:16

Error while setting up wibeee platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wibeee/sensor.py", line 198, in async_setup_entry
    device = await api.async_fetch_device_info(retries=5)
  File "/config/custom_components/wibeee/api.py", line 39, in async_fetch_device_info
    device_vars = {var['id']: var['value'] for var in values['values']['variable']}
KeyError: 'values'
```
Exemple (28/11 to 6/12) of activity, between the hass_wibeee component in HA and Wibeee Nest:
![ha](https://user-images.githubusercontent.com/78053830/205912904-e69d2258-ef21-4ff1-80b5-e8ded27585bf.png)
![wibeee](https://user-images.githubusercontent.com/78053830/205912945-a842d30c-124e-4e21-9aa6-bbb9c047b4a6.png)

**Comment by luuuis** [comment]
It looks like your Wibeee is not responding properly. In my experience, power cycling the device normally improves stability.

If you'd like me to look deeper into it I will need the debug logs.

https://github.com/luuuis/hass_wibeee/wiki/Troubleshooting

**Comment by ostracizado** [comment]
Checking the debug - timeline: 2min -, the errors that came up once in a while are:

```
Line 150357: 2022-12-09 09:44:47.073 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from Nest push: <Entity WIBEEE Power Factor L4: 0.770>
Line 150358: 2022-12-09 09:44:47.073 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:44:46 +0000] "GET /Wibeee/receiverLeap?mac=XXXXXXXXXXX&soft=4.4.164&model=WBB&time=1670579084&id=2702&gr=7&v1=230.46&v2=230.46&v3=230.46&vt=230.46&i1=4.61&i2=0.61&i3=0.00&it=5.22&a1=1059&a2=133&a3=0&at=926&r1=0&r2=0&r3=0&rt=0&f1=0.997&f2=-0.943&f3=0.000&ft=0.770&t1t=24.6&t11=4.6&t13=1.0&t15=0.4&t17=0.3&t19=0.0&t2t=0.0&t21=0.0&t23=0.0&t25=0.0&t27=0.0&t29=0.0&t3t=0.0&t31=0.0&t33=0.0&t35=0.0&t37=0.0&t39=0.0 HTTP/1.1" 200 171 "-" "-"
Line 150359: 2022-12-09 09:44:55.096 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:44:54 +0000] "POST /Wibeee/receiverAvgPost HTTP/1.1" 200 162 "-" "-"
Line 150360: 2022-12-09 09:44:56.169 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://192.168.2.139/en/status.xml: <response>
Line 150476: 2022-12-09 09:44:56.169 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml, will retry. ExpatError: not well-formed (invalid token): line 116, column 0
Line 150477: 2022-12-09 09:44:56.169 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.200s to retry http://192.168.2.139/en/status.xml...
Line 150480: 2022-12-09 09:44:57.536 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://192.168.2.139/en/status.xml: <response>
Line 150596: 2022-12-09 09:44:57.540 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from status.xml: <Entity WIBEEE Phase Voltage L1: 230.60>

Line 150724: 2022-12-09 09:45:07.080 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from Nest push: <Entity WIBEEE Power Factor L4: 0.801>
Line 150725: 2022-12-09 09:45:07.080 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:45:06 +0000] "GET /Wibeee/receiverLeap?mac=XXXXXXXXXXX&soft=4.4.164&model=WBB&time=1670579104&id=2712&gr=7&v1=230.76&v2=230.76&v3=230.76&vt=230.76&i1=4.71&i2=0.53&i3=0.00&it=5.24&a1=1082&a2=113&a3=0&at=969&r1=0&r2=0&r3=0&rt=0&f1=0.995&f2=-0.931&f3=0.000&ft=0.801&t1t=24.3&t11=4.7&t13=1.0&t15=0.4&t17=0.3&t19=0.0&t2t=0.0&t21=0.0&t23=0.0&t25=0.0&t27=0.0&t29=0.0&t3t=0.0&t31=0.0&t33=0.0&t35=0.0&t37=0.0&t39=0.0 HTTP/1.1" 200 171 "-" "-"
Line 150727: 2022-12-09 09:45:07.944 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml, will retry. ServerDisconnectedError: Server disconnected
Line 150728: 2022-12-09 09:45:07.944 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.200s to retry http://192.168.2.139/en/status.xml...
Line 150729: 2022-12-09 09:45:11.672 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://192.168.2.139/en/status.xml: <response>
Line 150845: 2022-12-09 09:45:11.672 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml, will retry. ExpatError: not well-formed (invalid token): line 90, column 27
Line 150846: 2022-12-09 09:45:11.672 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.400s to retry http://192.168.2.139/en/status.xml...
Line 150847: 2022-12-09 09:45:13.451 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://192.168.2.139/en/status.xml: <response>
Line 150963: 2022-12-09 09:45:13.455 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from status.xml: <Entity WIBEEE Phase Voltage L1: 230.98>

Line 151627: 2022-12-09 09:45:49.240 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from Nest push: <Entity WIBEEE Power Factor L4: 0.817>
Line 151628: 2022-12-09 09:45:49.241 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:45:49 +0000] "GET /Wibeee/receiverLeap?mac=XXXXXXXXXXX&soft=4.4.164&model=WBB&time=1670579146&id=2738&gr=7&v1=233.38&v2=233.38&v3=233.38&vt=233.38&i1=4.81&i2=0.50&i3=0.00&it=5.31&a1=1122&a2=108&a3=0&at=1013&r1=0&r2=0&r3=0&rt=0&f1=0.999&f2=-0.928&f3=0.000&ft=0.817&t1t=23.3&t11=4.8&t13=1.0&t15=0.4&t17=0.3&t19=0.0&t2t=0.0&t21=0.0&t23=0.0&t25=0.0&t27=0.0&t29=0.0&t3t=0.0&t31=0.0&t33=0.0&t35=0.0&t37=0.0&t39=0.0 HTTP/1.1" 200 171 "-" "-"
Line 151629: 2022-12-09 09:45:54.300 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:45:53 +0000] "POST /Wibeee/receiverAvgPost HTTP/1.1" 200 162 "-" "-"
Line 151630: 2022-12-09 09:45:56.266 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://192.168.2.139/en/status.xml: <response>
Line 151746: 2022-12-09 09:45:56.266 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml, will retry. ExpatError: not well-formed (invalid token): line 4, column 16
Line 151747: 2022-12-09 09:45:56.266 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.200s to retry http://192.168.2.139/en/status.xml...
Line 151750: 2022-12-09 09:45:57.577 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://192.168.2.139/en/status.xml: <response>
Line 151866: 2022-12-09 09:45:57.579 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from status.xml: <Entity WIBEEE Phase Voltage L1: 234.27>

Line 152793: 2022-12-09 09:46:48.261 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from Nest push: <Entity WIBEEE Power Factor L4: 0.802>
Line 152794: 2022-12-09 09:46:48.262 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:46:48 +0000] "GET /Wibeee/receiverLeap?mac=XXXXXXXXXXX&soft=4.4.164&model=WBB&time=1670579205&id=2768&gr=7&v1=232.98&v2=232.98&v3=232.98&vt=232.98&i1=4.67&i2=0.52&i3=0.00&it=5.19&a1=1083&a2=113&a3=0&at=970&r1=0&r2=0&r3=0&rt=0&f1=0.997&f2=-0.929&f3=0.000&ft=0.802&t1t=24.0&t11=4.6&t13=1.0&t15=0.4&t17=0.3&t19=0.0&t2t=0.0&t21=0.0&t23=0.0&t25=0.0&t27=0.0&t29=0.0&t3t=0.0&t31=0.0&t33=0.0&t35=0.0&t37=0.0&t39=0.0 HTTP/1.1" 200 171 "-" "-"
Line 152795: 2022-12-09 09:46:53.039 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml, will retry. ClientResponseError: 400, message='Expected HTTP/', url=URL('http://192.168.2.139/en/status.xml')
Line 152796: 2022-12-09 09:46:53.039 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.200s to retry http://192.168.2.139/en/status.xml...
Line 152797: 2022-12-09 09:46:53.471 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:46:52 +0000] "POST /Wibeee/receiverAvgPost HTTP/1.1" 200 289 "-" "-"
Line 152798: 2022-12-09 09:46:55.626 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml, will retry. ClientResponseError: 400, message='Expected HTTP/', url=URL('http://192.168.2.139/en/status.xml')
Line 152799: 2022-12-09 09:46:55.626 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.400s to retry http://192.168.2.139/en/status.xml...
Line 152802: 2022-12-09 09:46:56.903 DEBUG (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml, will retry. ClientResponseError: 400, message='Expected HTTP/', url=URL('http://192.168.2.139/en/status.xml')
Line 152803: 2022-12-09 09:46:56.903 DEBUG (MainThread) [custom_components.wibeee.api] Waiting 0.800s to retry http://192.168.2.139/en/status.xml...
Line 152804: 2022-12-09 09:46:58.436 ERROR (MainThread) [custom_components.wibeee.api] Error getting http://192.168.2.139/en/status.xml after 3 retries: ClientResponseError: 400, message='Expected HTTP/', url=URL('http://192.168.2.139/en/status.xml')
Line 152805: 2022-12-09 09:47:04.587 INFO (MainThread) [custom_components.wibeee.nest.access] 192.168.2.139 [09/Dec/2022:09:47:03 +0000] "POST /Wibeee/receiverAvgPost HTTP/1.1" 200 162 "-" "-"
Line 152808: 2022-12-09 09:47:08.973 DEBUG (MainThread) [custom_components.wibeee.api] RAW Response from http://192.168.2.139/en/status.xml: <response>
Line 152924: 2022-12-09 09:47:08.977 DEBUG (MainThread) [custom_components.wibeee.sensor] Updating from status.xml: <Entity WIBEEE Phase Voltage L1: 233.17>
```

**Comment by joaopedros2** [comment]
I have two devices, one for measuring consumption and the other for production. Sometimes I end up with the production one unavailable or both, and to solve the problem, I have to reload the integration to make it work again. This happens if I reboot HA. The integration doesn't start up completely.

**Comment by luuuis** [comment]
In [v4.0.0](https://github.com/luuuis/hass_wibeee/releases/tag/v4.0.0) polling is disabled by default (and will probably be removed completely in the future). Therefore, this problem does not occur any more.
