### ISSUE TITLE
Integration doesn't start when Wibeee XML API does not respond

### ISSUE THREAD

**Issue by joaopedros2** [luuuis/hass_wibeee#69]
When I restart HA, the integration doesn't start, and to solve the issue, I have to reload the integration entries.

![wibeee](https://github.com/luuuis/hass_wibeee/assets/50808090/23cc2917-e537-4e2c-b360-50cfaeb18fdd)

![wibeee_2](https://github.com/luuuis/hass_wibeee/assets/50808090/c724dac7-d02c-45fa-85a5-e2781cc5052e)

![wibeee_3](https://github.com/luuuis/hass_wibeee/assets/50808090/7c993651-6580-46a6-ab93-2e6d543c06fc)

LOGS
----------------------------------------------------------------------------------------------------------------------------------------
This error originated from a custom integration.

Logger: custom_components.wibeee.api
Source: custom_components/wibeee/api.py:73
Integration: wibeee (documentation, issues)
First occurred: 9:46:46 AM (28 occurrences)
Last logged: 12:36:10 PM

Error getting http://192.168.68.210/en/status.xml after 3 retries: ClientResponseError: 400, message="Expected HTTP/:\n\n b'AT+CIPSENDBUF=4,415'\n ^", url=URL('http://192.168.68.210/en/status.xml')
Error getting http://192.168.68.210/en/status.xml after 3 retries: ClientResponseError: 400, message="Expected HTTP/:\n\n b'</time>'\n ^", url=URL('http://192.168.68.210/en/status.xml')
Error getting http://192.168.68.210/en/status.xml after 3 retries: ServerDisconnectedError: Server disconnected
Error getting http://192.168.68.210/en/status.xml after 3 retries: TimeoutError:
Error getting http://192.168.68.210/en/status.xml after 3 retries: ClientResponseError: 400, message="Expected HTTP/:\n\n b'AT+CIPSENDBUF=4,412'\n ^", url=URL('http://192.168.68.210/en/status.xml')

----------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.components.sensor
Source: runner.py:188
Integration: Sensor (documentation, issues)
First occurred: 9:40:35 AM (1 occurrences)
Last logged: 9:40:35 AM

Setup of sensor platform wibeee is taking over 10 seconds.

----------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: 9:40:31 AM (1 occurrences)
Last logged: 9:40:31 AM

Error while setting up wibeee platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wibeee/sensor.py", line 207, in async_setup_entry
    initial_status = await api.async_fetch_status(retries=10)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wibeee/api.py", line 27, in async_fetch_status
    return status["response"]
           ~~~~~~^^^^^^^^^^^^
KeyError: 'response'

**Comment by luuuis** [comment]
Note to self: look at using `RestoreEntity` so that when the integration starts up the entities are restored (with unknown state) and available until such time as when the integration is able to fetch the new status.

**Comment by Mocheto** [comment]
same here! sometimes don't report anything, I press the reload button and it works. But suddenly stops again. Normally if I repeat the process it works, but other times I will need press two or three times more delayed on the time until works

**Comment by diegodepablos** [comment]
same problem here

**Comment by luuuis** [comment]
The problem is known, as mentioned above. The device's HTTP API (status.xml) is notoriously unstable. It is quite solid [once you configure Local Push](https://github.com/luuuis/hass_wibeee?tab=readme-ov-file#-configuring-local-push-optional-advanced), however.

"Me too" comments that do not add any information are not helpful, please refrain from commenting unless you have:
- additional logs from a different case not mentioned,
- proposed solutions,
- a correction to make to something that's been said,
- etc.

**Comment by diegodepablos** [comment]
Thank you for your reply. I've tried to setup it in the way you adviced, but unfortunately it doesn't work. Looks like only retrieves data when polls from the wibeee box.

I've enabled debug mode in HA and this is the log:

`2024-01-23 20:37:31.532 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:32.517 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:33.508 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:34.508 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:35.495 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:36.490 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:37.481 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:38.496 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:39.468 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:40.461 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:41.453 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:42.457 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:43.450 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:44.440 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:45.429 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:46.432 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:47.417 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:48.428 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:49.403 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:50.409 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:51.406 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:52.389 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver
2024-01-23 20:37:53.379 DEBUG (MainThread) [custom_components.wibeee.nest] Ignoring unexpected GET /Wibeee/receiver`

When I try to access http://xxxxx:8600 (get) I receive an empty file. I don't know if that is the supposed normal behaviour.

I'm a software engineer so if you can provide additional instructions to test it better it would be great.

Any help will be much appreciated.

Thanks.

**Comment by luuuis** [comment]
@diegodepablos that looks like a separate problem in the local push support. Looks like an easy fix, please open a new issue and we can go from there.

**Comment by luuuis** [comment]
Thanks @Mocheto but there is no further information required because the problem is well known. It's the same underlying cause as #52: Wibeee device returns garbage sometimes.

The only thing to do is work around the problem, if possible (using `RestoreEntity` or another approach to be determined).
