### ISSUE TITLE
Integration failed to start

### ISSUE THREAD

**Issue by antonio-fiol** [luuuis/hass_wibeee#77]
I did not have debug logs enabled, but caught this on the log.

2024-01-17 21:27:39.015 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wibeee platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wibeee/sensor.py", line 228, in async_setup_entry
    device = await api.async_fetch_device_info(retries=5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wibeee/api.py", line 67, in async_fetch_device_info
    device_vars = {var['id']: var['value'] for var in values['values']['variable']}
                                                      ~~~~~~^^^^^^^^^^
KeyError: 'values'

**Comment by antonio-fiol** [comment]
I enabled debug and restarted HA and it started correctly.
This sounds like a corner case...

**Comment by luuuis** [comment]
This happens when Wibeee does not respond with a valid XML payload (another example [here](https://github.com/luuuis/hass_wibeee/issues/52)). If it happens again you do not need to restart HA, it's enough to reload the integration.

![Settings – Home Assistant 2024-01-18 19-29-44](https://github.com/luuuis/hass_wibeee/assets/161006/7723f2ca-08de-4d0a-bd0c-d17c28169d27)
